install:
	mvn install:install-file -Dfile=gettext-commons-0.9.6.jar -DgroupId=org.xnap.commons -Dversion=0.9.6 -Dpackaging=jar -DartifactId=gettext-commons
	@echo Installed maven-gettext-plugin in local maven repository.
